ptdify/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'', include('ptdify.web.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
)

urlpatterns += staticfiles_urlpatterns()

ptdify/web/urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView
from web.views import *

urlpatterns = patterns('',
    url(r'^$',                  HomeView.as_view(),             name="home"),
    url(r'^ajax/autocomplete$', AutocompleteView.as_view(),     name="autocomplete"),
)

ptdify/web/models.py
from django.contrib.auth.models import User
from django.db import models
from web.managers import UserManager

# Abstract base classes
class UserModel(models.Model):
    user = models.ForeignKey(User)

    # Managers
    objects = UserManager()

    class Meta:
        abstract = True

class UserRealmModel(UserModel):
    realm = models.ForeignKey('Realm',blank=True,null=True)

    class Meta:
        abstract = True

# Normal classes
ACTIONSTATUS = (
    ('W', 'Waiting'),
    ('N', 'Next'),
    ('F', 'Future'),
)

class Action(UserRealmModel):
    description = models.CharField(max_length=100)
    notes = models.TextField(blank=True)
    contact = models.ForeignKey('Contact',blank=True,null=True)
    context = models.ForeignKey('Context')
    project = models.ForeignKey('Project',blank=True,null=True)
    dependsOn = models.ForeignKey('Action',blank=True,null=True)
    # are these still necessary?
    # due = models.DateField(blank=True,null=True)
    # showFrom = models.DateField(blank=True,null=True)
    completed = models.BooleanField()
    status = models.CharField(max_length=1, choices=ACTIONSTATUS, default='N')

    def __unicode__(self):
        return self.description

    def save(self, *args, **kwargs):
        # if:
        # - we are not yet completed
        # AND
        # - we are depending on some other action
        # then become future if:
        #       - the action we depend on is future 
        #       OR
        #       - the action we depend on is not yet completed
        if not self.completed and self.dependsOn_id is not None:
            if self.dependsOn.status == 'F' or not self.dependsOn.completed:
                self.status = 'F'

        super(Action, self).save(*args, **kwargs) # Call the "real" save() method.

        # some postprocessing
        if self.completed: # all future actions depending on this one become next
            searchFor = 'F'
            turnInto = 'N'
        else: # all next actions depending on this one become future
            searchFor = 'N'
            turnInto = 'F'
        
        depending = self.action_set.filter(completed=False).filter(status__exact=searchFor)
        for d in depending:
            d.status = turnInto
            d.save()

class Area(UserRealmModel):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Contact(UserRealmModel):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Context(UserRealmModel):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Project(UserRealmModel):
    active = models.BooleanField(default=True)
    area = models.ForeignKey('Area',blank=True,null=True)
    description = models.TextField(blank=True)
    defaultContact = models.ForeignKey(Contact,blank=True,null=True)
    defaultContext = models.ForeignKey(Context)
    name = models.CharField(max_length=50)
    order = models.PositiveIntegerField(blank=True,null=True)

    def __unicode__(self):
        return self.name

class Realm(UserModel):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

ptdify/web/views.py
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from web.genericviews import LoggedInView
from web.mixins import JSONResponseMixin
from web.util.search import Search

class HomeView(LoggedInView, TemplateView):
    template_name = "home.html"

class AutocompleteView(View, JSONResponseMixin):
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden("Forbidden: not logged in")

        return super(AutocompleteView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        query =  request.GET.getlist('query')

        try:
            search = Search.fromJSON(query)     
        except ValueError as e:
            return HttpResponseBadRequest("Bad request: %s" % e)

        completed = search.autoComplete(10) # TODO remove magic number

        result_list = [[block.as_list() for block in suggestion] for suggestion in completed]

        return self.render_to_response(result_list)

ptdify/web/templates/base.html
{% load url from future %}
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}css/base.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}css/autocomplete.css" />
    <script src="{{ STATIC_URL }}js/jquery-1.6.2.js" ></script>
    <script src="{{ STATIC_URL }}js/ui/jquery.ui.core.js"></script>
    <script src="{{ STATIC_URL }}js/ui/jquery.ui.widget.js"></script>
    <script src="{{ STATIC_URL }}js/ui/jquery.ui.position.js"></script>
    <script src="{{ STATIC_URL }}js/ui/jquery.ui.autocomplete.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.json-2.2.js"></script>
    <script language="text/javascript">var autocompleteUrl = "{% url 'autocomplete' %}";</script>
    <script src="{{ STATIC_URL }}js/smartbox/smartbox.js"></script>	
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

ptdify/web/templates/home.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<div id="loginWrapper">
logged in as: {{ username }} <a href="{% url 'logout' %}">(logout)</a>
</div>

<div id="smartboxWrapper">

	<div id="searchtags">
		<ul></ul>
	</div>

	<div class="ui-widget left">
		<form id="smartboxform">

			<input id="smartbox" value="" size="25" />
		</form>
	</div>

	<div class="clear"></div>
</div>
{% endblock %}

ptdify/web/templates/web/action_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Actions</h2>
    <ul>
        {% for action in object_list %}
            <li>{{ action.description }}</li>
            <ul>
                {% if action.project %} 
                <li>{{ action.project.name }}</li>
                {% endif %}
                {% if action.dependsOn %} 
                <li>{{ action.dependsOn.description }}</li>
                {% endif %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

ptdify/web/templates/web/area_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Areas</h2>
    <ul>
        {% for area in object_list %}
            <li>{{ area.name }}</li>
            <h3>Actions</h3>
            <ul>
                {% for action in area.action_set.all %}
                    <li>{{ action.description }}</li>
                {% endfor %}
            </ul>
            <h3>Contexts</h3>
            <ul>
                {% for context in area.context_set.all %}
                    <li>{{ context.name }}</li>
                {% endfor %}
            </ul>
            <h3>Projects</h3>
            <ul>
                {% for project in area.project_set.all %}
                    <li>{{ project.name }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

ptdify/web/templates/web/context_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Context</h2>
    <ul>
        {% for context in object_list %}
            <li>{{ context.name }}</li>
            <ul>
                {% for action in context.action_set.all %}
                    <li>{{ action.description }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}

ptdify/web/templates/web/project_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Project</h2>
    <ul>
        {% for project in object_list %}
            <li>{{ project.name }}</li>
            <ul>
                {% for action in project.action_set.all %}
                    <li>{{ action.description }}</li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
{% endblock %}